import { ScrollView, View, Text, StyleSheet } from "react-native";

const C = {
  bg:          "#080a07",
  glass:       "rgba(255,255,255,0.08)" as const,
  glassBorder: "rgba(255,255,255,0.14)" as const,
  accent:      "#c2d635",
  accentDim:   "rgba(194,214,53,0.15)" as const,
  amber:       "#f5a623",
  amberDim:    "rgba(245,166,35,0.15)" as const,
  red:         "#e05530",
  redDim:      "rgba(224,85,48,0.15)" as const,
  textPrimary: "#ffffff",
  textMuted:   "#888",
  textBody:    "#bbb",
};

// ── Content ───────────────────────────────────────────────────────────────────

const SECTIONS = [
  {
    title: "The score (0–100)",
    accentColor: C.accent,
    accentDimColor: C.accentDim,
    body: `Every vehicle Augur checks receives a score between 0 and 100. It's calculated from four inputs: MOT history reliability, odometer consistency, active safety recalls, and fault record prevalence from Augur's database.

MOT history carries the most weight. We look at both pass/fail outcomes and the specific failure reasons — a car that repeatedly fails on brakes is penalised more than one with occasional light bulb failures.

The score is designed to be conservative. Uncertainty pushes the score down, not up. If we have fewer than 10 records for a model, we widen the penalty margin and flag limited data directly on the results screen.`,
  },
  {
    title: "Fraud detection",
    accentColor: C.red,
    accentDimColor: C.redDim,
    body: `Augur checks for two types of odometer manipulation.

The first is regression-based. We fit a curve to all MOT mileage readings across the vehicle's life. Any reading that falls more than 15% below the expected value at that test date is flagged as a likely rollback.

The second is gap detection. If the mileage drops between two consecutive MOT tests — even by a single mile — that's flagged immediately, regardless of magnitude. Genuine mileage never decreases.

Both checks run against the DVSA anonymised MOT bulk dataset. When either fires, the score is reduced and the fraud flag is surfaced prominently on the results screen with the specific test dates involved.`,
  },
  {
    title: "Diagnosis confidence",
    accentColor: C.amber,
    accentDimColor: C.amberDim,
    body: `When you describe a symptom, Augur runs it against its fault database in two steps.

First, a language model extracts keywords from your description and classifies which vehicle system is most likely involved (brakes, engine, steering, etc.). Those keywords query the indexed fault records.

Second, the same model scores each candidate fault for relevance to your specific symptom on a scale of 0–1. The final confidence figure blends relevance (70% weight) with provenance (30% weight).

Provenance bonuses reflect source reliability: DVSA safety recalls score highest (1.0), followed by curated records from Honest John and Augur Research (0.8), with MOT aggregate data lowest (0.5). A fault needs at least 25% relevance to appear in results — this prevents unrelated recalls from surfacing just because they match the make and model.`,
  },
  {
    title: "Data sources",
    accentColor: C.accent,
    accentDimColor: C.accentDim,
    body: `Augur draws from three external sources, each tagged on every record it contributes.

DVSA MOT Bulk Dataset — the UK Government's anonymised record of every MOT test conducted in Great Britain. Augur's current dataset covers 2024 and contains data on millions of test outcomes and failure reasons, aggregated by make, model, and year range.

DVSA Vehicle Recall Database — the official register of manufacturer safety recalls issued in the UK. Recalls are matched to your vehicle by make, model, and build date. An active recall means the defect has been formally acknowledged by the manufacturer and a remedy exists.

Augur Research — faults manually curated by the Augur team, covering issues that don't appear in MOT records: electrical gremlins, premature wear patterns, recurring mechanical failures reported in owner communities. These are explicitly labelled as "Augur Research" wherever they appear.`,
  },
  {
    title: "AI summaries",
    accentColor: C.amber,
    accentDimColor: C.amberDim,
    body: `Short text summaries on the recommendations and results screens are generated by a large language model (Llama 3.1 8B via Groq). The model does not browse the web or draw on general training knowledge about specific cars.

Every summary is generated from a prompt that contains only verified records pulled from Augur's database at the time of the request: MOT failure frequencies, curated fault descriptions, and active recalls. The model is explicitly instructed not to reference anything outside that data.

This means a summary for a car with no database records will say so directly, rather than filling the gap with generic advice. The attribution line ("Based on N verified records") reflects exactly how many DB rows were included in the prompt.`,
  },
  {
    title: "What Augur is not",
    accentColor: C.red,
    accentDimColor: C.redDim,
    body: `Augur is a decision-support tool, not a guarantee. A high score means the vehicle's history looks clean against the data we hold — it doesn't mean the car is problem-free. We don't have access to private service records, accident history, or independent inspections.

The diagnosis module is a triage aid. It surfaces statistically likely explanations for a symptom based on known faults for that model. It cannot substitute for a physical inspection by a qualified mechanic.

Before committing to any purchase, Augur recommends an independent pre-purchase inspection (PPI) from a RAC or AA approved centre.`,
  },
];

// ── Component ─────────────────────────────────────────────────────────────────

export default function TransparencyScreen() {
  return (
    <ScrollView
      style={styles.container}
      contentContainerStyle={styles.content}
      showsVerticalScrollIndicator={false}
    >
      <Text style={styles.intro}>
        Augur is built on verifiable data. This page explains exactly how the numbers are produced.
      </Text>

      {SECTIONS.map((section, i) => (
        <View
          key={i}
          style={[
            styles.card,
            { borderLeftColor: section.accentColor, backgroundColor: section.accentDimColor },
          ]}
        >
          <Text style={[styles.cardTitle, { color: section.accentColor }]}>
            {section.title}
          </Text>
          <Text style={styles.cardBody}>{section.body}</Text>
        </View>
      ))}

      <View style={styles.footer}>
        <Text style={styles.footerText}>
          Data sources: DVSA MOT Bulk Dataset · DVSA Vehicle Recall Register · Augur Research
        </Text>
        <Text style={styles.footerText}>
          AI inference: Llama 3.1 8B (Groq) · DB-grounded prompts only
        </Text>
      </View>
    </ScrollView>
  );
}

// ── Styles ────────────────────────────────────────────────────────────────────

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: C.bg,
  },
  content: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 48,
    gap: 16,
  },

  intro: {
    fontSize: 14,
    color: C.textMuted,
    lineHeight: 21,
    marginBottom: 4,
  },

  card: {
    borderRadius: 12,
    borderLeftWidth: 3,
    padding: 16,
    gap: 10,
  },
  cardTitle: {
    fontSize: 14,
    fontWeight: "700",
    letterSpacing: 0.3,
    textTransform: "uppercase",
  },
  cardBody: {
    fontSize: 14,
    color: C.textBody,
    lineHeight: 22,
  },

  footer: {
    marginTop: 8,
    gap: 4,
  },
  footerText: {
    fontSize: 11,
    color: C.textMuted,
    lineHeight: 17,
  },
});
